name: functional
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2

  #comparing objects
  equatable: ^2.0.5

  #storage local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # service locator
  get_it: ^7.6.4

  #routing
  go_router: ^12.1.0

  # functional programming
  cupertino_icons: ^1.0.5

  #Apis and networking
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3

  #reading json animation file
  lottie: ^2.7.0

  # logging data managment

  # svg images
  flutter_svg: ^2.0.9
  # ui slider images
  carousel_slider: ^4.2.1
  #url launcher
  url_launcher: ^6.1.14

  # cashed images networking
  cached_network_image: ^3.3.0
  envied: ^0.5.2

  # intel
  intl: ^0.18.1
  # form validation
  formz: ^0.6.1
  #otp
  flutter_otp_text_field: ^1.1.1
  # local notification
  animate_do: ^3.1.2

  share_plus: ^7.2.1

  # localizations (languages)
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  envied_generator: ^0.5.2
  retrofit_generator: ^8.0.3
  json_serializable: ^6.7.1
  mockito: ^5.4.3

flutter_assets:
  assets_path: assets/
  output_path: lib/core/resources_manager
  filename: assets.dart
flutter:
  uses-material-design: true
  #assets images,json,sound,env file,translations,videos and fonts
  assets:
    - assets/img/
    - assets/json/
    - assets/translations/
    - .env

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300

    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
